// Project info

name := "play2-sample-module"

organization := "com.github.masahito"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.9.1"

// Dependencies

libraryDependencies += "play" %% "play" % "2.0"

// libraryDependencies += "play" %% "play-test" % "2.0" % "test"

// Test dependencies

libraryDependencies ++= Seq(
    "org.specs2" %% "specs2" % "1.8.2" % "test"
)

// Configuration required for deploying to sonatype

publishMavenStyle := true

publishTo <<= version { (v: String) =>
  val nexus = "https://oss.sonatype.org/"
  if (v.trim.endsWith("SNAPSHOT"))
    Some("snapshots" at nexus + "content/repositories/snapshots")
  else
    Some("releases"  at nexus + "service/local/staging/deploy/maven2")
}

pomIncludeRepository := { _ => false }

publishArtifact in Test := false

pomExtra := (
  <url>http://github.com/masahitojp/play2-sample-module</url>
  <inceptionYear>2012</inceptionYear>
  <licenses>
    <license>
      <name>Apache 2</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
      <comments>A business-friendly OSS license</comments>
    </license>
  </licenses>
  <scm>
    <url>git@github.com:masahitojp/play2-sample-module.git</url>
    <connection>scm:git:git@github.com:masahitojp/play2-sample-module.git</connection>
  </scm>
  <developers>
    <developer>
      <name>Nakamura Masato</name>
      <email>randomstep@gmail.com</email>
      <url>http://masahito.me/</url>
      <roles>
        <role>Author</role>
      </roles>
      <organization>Nakamura Masato</organization>
    </developer>
  </developers>)
